// Shared test helpers and fast-check generators for itinerary-utils tests.
//
// These are used by both the property-test and unit-test files. They are NOT
// test files themselves (no `.test.` suffix), so vitest's include pattern will
// not treat them as suites.

import * as fc from 'fast-check'
import type { ItineraryLeg, HopResult, TravelMode } from './itinerary-utils'

// ── Reference date math (independent of the module under test) ───────

/** Correct Gregorian leap-year rule. */
export function isLeapYear(y: number): boolean {
  return (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0
}

/** Days in a month, m is 1-12. */
export function daysInMonth(y: number, m: number): number {
  switch (m) {
    case 1:
    case 3:
    case 5:
    case 7:
    case 8:
    case 10:
    case 12:
      return 31
    case 4:
    case 6:
    case 9:
    case 11:
      return 30
    case 2:
      return isLeapYear(y) ? 29 : 28
    default:
      return 0
  }
}

function pad2(n: number): string {
  return n < 10 ? `0${n}` : `${n}`
}

/** Format numeric parts into a zero-padded 'YYYY-MM-DD' string. */
export function fmt(y: number, m: number, d: number): string {
  const year = y < 1000 ? `000${y}`.slice(-4) : `${y}`
  return `${year}-${pad2(m)}-${pad2(d)}`
}

/**
 * Independent reference "days since a fixed epoch" for a valid (y,m,d).
 * Uses the Julian Day Number algorithm — deliberately a separate implementation
 * from the module so the property test has a genuine oracle.
 */
export function refDaysFromEpoch(y: number, m: number, d: number): number {
  const a = Math.floor((14 - m) / 12)
  const year = y + 4800 - a
  const month = m + 12 * a - 3
  const jdn =
    d +
    Math.floor((153 * month + 2) / 5) +
    365 * year +
    Math.floor(year / 4) -
    Math.floor(year / 100) +
    Math.floor(year / 400) -
    32045
  return jdn - 2440588
}

// ── Generators ───────────────────────────────────────────────────────

/** A valid 'YYYY-MM-DD' string across 1900..2100, valid for the chosen month. */
export const ymd: fc.Arbitrary<string> = fc
  .record({
    y: fc.integer({ min: 1900, max: 2100 }),
    m: fc.integer({ min: 1, max: 12 }),
  })
  .chain(({ y, m }) =>
    fc.integer({ min: 1, max: daysInMonth(y, m) }).map((d) => fmt(y, m, d))
  )

/**
 * An ordered pair [start, end] with end >= start. Generated by picking a start
 * ymd then adding a non-negative day offset via the reference math, so the pair
 * is always valid and correctly ordered.
 */
export const orderedPair: fc.Arbitrary<[string, string]> = ymd
  .chain((start) =>
    fc.integer({ min: 0, max: 800 }).map((offset) => {
      // Walk forward `offset` days from `start` using reference arithmetic.
      let [ys, ms, ds] = start.split('-').map(Number)
      let remaining = offset
      while (remaining > 0) {
        const dim = daysInMonth(ys, ms)
        if (ds < dim) {
          ds += 1
        } else {
          ds = 1
          ms += 1
          if (ms > 12) {
            ms = 1
            ys += 1
          }
        }
        remaining -= 1
      }
      return [start, fmt(ys, ms, ds)] as [string, string]
    })
  )

/**
 * Strings that are NOT valid calendar dates. A mix of hand-picked malformed
 * values and generated ones; the generated impossible-day branch is guarded so
 * it can never accidentally be a real date.
 */
export const invalidDate: fc.Arbitrary<string> = fc.oneof(
  fc.constantFrom(
    '2024-13-01', // month 13
    '2024-00-10', // month 00
    '2024-01-00', // day 00
    '2024-02-30', // Feb 30 never exists
    '2024-04-31', // April has 30 days
    '2024-1-1', // not zero-padded
    '2024/01/01', // wrong separators
    'not-a-date',
    '', // empty
    '2023-02-29', // non-leap Feb 29
    '99999-01-01', // 5-digit year
    '2024-06-1', // single-digit day
    '2024-6-15' // single-digit month
  ),
  // A day that is impossible for its month: pick month 2 with day 30/31, or a
  // 30-day month with day 31. All are guaranteed invalid.
  fc
    .record({
      y: fc.integer({ min: 1900, max: 2100 }),
      pick: fc.constantFrom(
        { m: 2, d: 30 },
        { m: 2, d: 31 },
        { m: 4, d: 31 },
        { m: 6, d: 31 },
        { m: 9, d: 31 },
        { m: 11, d: 31 }
      ),
    })
    .map(({ y, pick }) => fmt(y, pick.m, pick.d))
)

/**
 * Like `orderedPair` but with a small span (0..45 days). Used by the leg
 * generator so that day-by-day walks over timeline bounds (Property 5) stay
 * fast, while still routinely crossing month, year, and leap-day boundaries.
 */
export const boundedPair: fc.Arbitrary<[string, string]> = ymd.chain((start) =>
  fc.integer({ min: 0, max: 45 }).map((offset) => {
    let [ys, ms, ds] = start.split('-').map(Number)
    let remaining = offset
    while (remaining > 0) {
      const dim = daysInMonth(ys, ms)
      if (ds < dim) {
        ds += 1
      } else {
        ds = 1
        ms += 1
        if (ms > 12) {
          ms = 1
          ys += 1
        }
      }
      remaining -= 1
    }
    return [start, fmt(ys, ms, ds)] as [string, string]
  })
)

const modes: TravelMode[] = ['drive', 'ferry', 'flight', 'train', 'other']

let keyCounter = 0
/** Unique-ish key generator so legs in a list have distinct _key values. */
export const uniqueKey: fc.Arbitrary<string> = fc
  .integer({ min: 0, max: 1_000_000 })
  .map((n) => `leg-${n}-${keyCounter++}`)

const coordinates: fc.Arbitrary<{ lat: number; lng: number }> = fc.record({
  lat: fc.double({ min: -90, max: 90, noNaN: true }),
  lng: fc.double({ min: -180, max: 180, noNaN: true }),
})

/** A generator for a single ItineraryLeg with an ordered start/end pair. */
export const leg: fc.Arbitrary<ItineraryLeg> = fc
  .record({
    _key: uniqueKey,
    label: fc.string({ minLength: 1, maxLength: 20 }).filter((s) => s.trim() !== ''),
    country: fc.option(fc.string({ minLength: 1, maxLength: 12 }), { nil: undefined }),
    pair: boundedPair,
    omitEnd: fc.boolean(),
    coordinates: fc.option(coordinates, { nil: undefined }),
    travelModeIn: fc.constantFrom(...modes),
    departureCountry: fc.option(fc.string({ minLength: 1, maxLength: 12 }), { nil: undefined }),
    notes: fc.option(fc.string({ maxLength: 30 }), { nil: undefined }),
  })
  .map((r) => {
    const [startDate, endDate] = r.pair
    const out: ItineraryLeg = {
      _type: 'itineraryLeg',
      _key: r._key,
      label: r.label,
      startDate,
      travelModeIn: r.travelModeIn,
    }
    if (!r.omitEnd) out.endDate = endDate
    if (r.country !== undefined) out.country = r.country
    if (r.coordinates !== undefined) out.coordinates = r.coordinates
    if (r.departureCountry !== undefined) out.departureCountry = r.departureCountry
    if (r.notes !== undefined) out.notes = r.notes
    return out
  })

/** A list of legs (0..6). */
export const legList: fc.Arbitrary<ItineraryLeg[]> = fc.array(leg, { minLength: 0, maxLength: 6 })

/**
 * A list of legs whose start dates are all clustered within a bounded window
 * (a base date plus a 0..90 day offset), each spanning 0..30 days. This keeps
 * the overall timeline bounds small (weeks, not centuries) so tests that walk
 * every day between the earliest start and latest end (e.g. Property 5) run
 * quickly, while still exercising overlaps, gaps, single-day legs, and month
 * boundaries. Legs are anchored to the same base year/month so the min→max span
 * cannot blow up the way an unconstrained list can.
 */
export const clusteredLegList: fc.Arbitrary<ItineraryLeg[]> = ymd.chain((base) =>
  fc.array(
    fc.record({
      _key: uniqueKey,
      label: fc.string({ minLength: 1, maxLength: 12 }).filter((s) => s.trim() !== ''),
      country: fc.option(fc.string({ minLength: 1, maxLength: 8 }), { nil: undefined }),
      startOffset: fc.integer({ min: 0, max: 90 }),
      span: fc.integer({ min: 0, max: 30 }),
      omitEnd: fc.boolean(),
    }),
    { minLength: 0, maxLength: 6 }
  ).map((specs) =>
    specs.map((spec) => {
      const walk = (from: string, n: number): string => {
        let [y, m, d] = from.split('-').map(Number)
        for (let k = 0; k < n; k++) {
          const dim = daysInMonth(y, m)
          if (d < dim) d += 1
          else if (m < 12) { m += 1; d = 1 }
          else { y += 1; m = 1; d = 1 }
        }
        return fmt(y, m, d)
      }
      const startDate = walk(base, spec.startOffset)
      const endDate = walk(startDate, spec.span)
      const out: ItineraryLeg = {
        _type: 'itineraryLeg',
        _key: spec._key,
        label: spec.label,
        startDate,
        travelModeIn: 'drive',
      }
      if (!spec.omitEnd) out.endDate = endDate
      if (spec.country !== undefined) out.country = spec.country
      return out
    })
  )
)

/** Non-negative metres, including 0 and large values. */
export const meters: fc.Arbitrary<number> = fc.double({ min: 0, max: 1e8, noNaN: true })

/** Non-negative seconds, including 0 and large values. */
export const seconds: fc.Arbitrary<number> = fc.double({ min: 0, max: 1e8, noNaN: true })

/** A HopResult mixing ok:true (with finite non-negative metrics) and ok:false. */
export const hopResult: fc.Arbitrary<HopResult> = fc.oneof(
  fc
    .record({
      key: fc.string({ minLength: 1, maxLength: 10 }),
      distanceMeters: meters,
      durationSeconds: seconds,
    })
    .map((r) => ({ ...r, ok: true } as HopResult)),
  fc
    .record({
      key: fc.string({ minLength: 1, maxLength: 10 }),
      error: fc.constantFrom('no-route', 'coords-needed'),
    })
    .map((r) => ({ key: r.key, ok: false, error: r.error } as HopResult))
)

export const hopResultList: fc.Arbitrary<HopResult[]> = fc.array(hopResult, {
  minLength: 0,
  maxLength: 8,
})
